version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:2.19.4
    container_name: portainer_server
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443" # HTTPS UI Access
      - "8000:8000" # Edge Agent Tunnel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
